### ISSUE TITLE
Delivery car is locked

### ISSUE THREAD

**Issue by ghost** [tcantrell/qb-oxyrun#1]
Hello, there is no error in the code. However when after speaking to the dealer and given the delivery car. when going up to the delivery car, the car is locked. Any way to fix this? 

I really appreciate the help!

**Comment by tcantrell** [comment]
Ill take a look at the script, but try lockpicking it. Let me know. I thought I bypassed that feature, so when you get the car spawned it was ready to go. But I recently changed my qb-vehiclekeys resource, so that might be the issue.
